# Generated by Django 3.2.7 on 2021-10-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_products_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='customer_id',
        ),
    ]
