# Generated by Django 3.2.7 on 2021-10-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211004_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='locality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
