# Generated by Django 3.2.7 on 2021-10-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='admin',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customerinfo',
            old_name='profile_pic',
            new_name='user_image',
        ),
    ]
