# Generated by Django 3.2.7 on 2021-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211004_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller')], default=1, max_length=2),
        ),
    ]
