# Generated by Django 3.2.7 on 2021-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_products_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller')], max_length=2),
        ),
    ]
