# Generated by Django 3.2.7 on 2021-10-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211004_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='label',
            field=models.CharField(choices=[('New', 'New'), ('Best Seller', 'Best Seller'), ('Clearance', 'Clearance'), ('Ever Green', 'Ever Green')], max_length=20),
        ),
    ]
