# Generated by Django 3.2.7 on 2021-10-06 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_products_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOrdered',
            new_name='Kart',
        ),
    ]
