# Generated by Django 3.2.7 on 2021-10-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_productordered_kart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kart',
            name='total_price',
        ),
    ]
