# Generated by Django 3.2.7 on 2021-10-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_kart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
