# Generated by Django 3.2.7 on 2021-10-07 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_alter_kart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kart',
            name='ordered',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('payment_choice', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Net Banking', 'Net Banking'), ('UPI', 'UPI'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card')], max_length=20)),
                ('items', models.ManyToManyField(to='app.Kart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
