# Generated by Django 3.2.7 on 2021-10-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_order_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='kart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
