# Generated by Django 3.2.7 on 2021-10-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_kart_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='final_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='original_price',
            field=models.FloatField(default=0),
        ),
    ]
