# Generated by Django 3.2.7 on 2021-10-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20211008_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.payment'),
        ),
    ]
