# Generated by Django 3.2.7 on 2021-10-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_orderplaced_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment_choice',
        ),
    ]
