# Generated by Django 3.2.7 on 2021-10-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_orderplaced_payment_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='save_address',
        ),
    ]
