# Generated by Django 3.2.7 on 2021-10-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20211008_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='user',
        ),
    ]
