# Generated by Django 3.2.7 on 2021-10-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20211008_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedItems',
        ),
    ]
