# Generated by Django 3.2.7 on 2021-10-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_ordereditems_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='items',
            field=models.ManyToManyField(to='app.Products'),
        ),
        migrations.DeleteModel(
            name='OrderedItems',
        ),
    ]
