# Generated by Django 3.2.7 on 2021-10-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20211011_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
