# Generated by Django 3.2.7 on 2021-10-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20211011_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kart',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='items',
            field=models.ManyToManyField(to='app.Products'),
        ),
    ]
